/** Build-time-ish keyword chunk index over docs (no embeddings). */

export type DocChunk = {
  id: string;
  title: string;
  path: string;
  text: string;
  keywords: string[];
};

/** Compact static index — regenerated by scripts/build-ai-docs-index.mjs when docs change. */
export const DOC_CHUNKS: DocChunk[] = [
  {
    id: "engine-ecs",
    title: "ECS",
    path: "engine/overview",
    text: "world_create entity_create transform2d_set sprite_set world_step world_draw scene_load",
    keywords: ["ecs", "entity", "world", "scene", "sprite", "transform"],
  },
  {
    id: "engine-3d",
    title: "3D",
    path: "engine/intrinsics",
    text: "scene3d_init mesh3d_box camera3d_perspective world_draw3d mesh_load_gltf scene3d_set_ambient fog",
    keywords: ["3d", "mesh", "gltf", "webgpu", "light", "ambient", "fog", "draw3d"],
  },
  {
    id: "physics",
    title: "Physics",
    path: "projects/physics",
    text: "rigidbody2d_set_vel grounded collision_count collider2d_set camera2d_follow prefab_spawn triggers",
    keywords: ["physics", "collision", "rigidbody", "collider", "jump", "grounded", "prefab"],
  },
  {
    id: "netlify",
    title: "Netlify",
    path: "projects/netlify",
    text: "netlify.toml ide dist deploy GITHUB_PAGES false export web static",
    keywords: ["netlify", "deploy", "host", "publish", "export"],
  },
  {
    id: "language",
    title: "Juni language",
    path: "language/syntax",
    text: "fn main frame state i32 f32 indentation modules import export wasm",
    keywords: ["juni", "syntax", "fn", "state", "type", "module"],
  },
];

export function retrieveDocContext(query: string, k = 3): string {
  const tokens = query
    .toLowerCase()
    .split(/[^a-z0-9_]+/)
    .filter((t) => t.length > 2);
  if (!tokens.length) return "";
  const scored = DOC_CHUNKS.map((chunk) => {
    let score = 0;
    for (const t of tokens) {
      if (chunk.keywords.includes(t)) score += 3;
      if (chunk.text.toLowerCase().includes(t)) score += 1;
      if (chunk.title.toLowerCase().includes(t)) score += 2;
    }
    return { chunk, score };
  })
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, k);
  if (!scored.length) return "";
  return scored
    .map((s) => `[${s.chunk.title}] ${s.chunk.text}`)
    .join("\n");
}
