import type * as Monaco from "monaco-editor";

export const JUNI_LANGUAGE_ID = "juni";

export function registerJuniLanguage(monaco: typeof Monaco): void {
  monaco.languages.register({ id: JUNI_LANGUAGE_ID });
  monaco.languages.setMonarchTokensProvider(JUNI_LANGUAGE_ID, {
    keywords: [
      "fn",
      "struct",
      "let",
      "state",
      "if",
      "else",
      "while",
      "for",
      "in",
      "break",
      "continue",
      "return",
      "new",
      "delete",
      "ref",
      "mut",
      "true",
      "false",
      "and",
      "or",
      "not",
      "print",
      "sqrt",
      "sin",
      "cos",
      "tan",
      "abs",
      "floor",
      "ceil",
      "min",
      "max",
      "rand",
      "now",
      "frame",
      "clamp",
      "lerp",
      "pow",
      "sign",
      "fmod",
      "smoothstep",
      "deg_to_rad",
      "rad_to_deg",
      "dist2",
      "pi",
      "str_len",
      "str_eq",
      "str_concat",
      "str_substr",
      "len2",
      "dot2",
      "abs_i32",
      "imin",
      "imax",
      "iclamp",
      "canvas_init",
      "canvas_clear",
      "canvas_fill_rect",
      "canvas_fill_circle",
      "canvas_fill_text",
      "canvas_draw_line",
      "canvas_stroke_rect",
      "asset_load_str",
      "sprite_draw",
      "mesh_load_obj",
      "gpu_clear",
      "gpu_draw_triangle",
      "key_down",
      "mouse_x",
      "mouse_y",
      "mouse_down",
      "scene3d_init",
      "scene3d_clear",
      "scene3d_draw",
      "scene3d_create_node",
      "scene3d_set_parent",
      "camera3d_perspective",
      "camera3d_look_at",
      "camera3d_orbit",
      "mesh3d_box",
      "mesh3d_custom",
      "mesh3d_set_pose",
      "mesh3d_rotate",
      "material3d_color",
      "mesh3d_set_material",
      "aabb_overlap",
      "aabb_resolve_x",
      "aabb_resolve_y",
      "audio_load",
      "audio_play",
      "audio_play_loop",
      "audio_set_volume",
      "world_create",
      "entity_create",
      "entity_destroy",
      "entity_set_tag",
      "entity_find_by_tag",
      "transform2d_set",
      "transform3d_set",
      "sprite_set",
      "mesh3d_attach",
      "world_step",
      "scene_load",
      "camera2d_set",
      "tilemap_load",
      "tilemap_attach",
      "world_draw",
      "material3d_texture",
      "light3d_directional",
      "light3d_point",
      "mesh_load_gltf",
      "gamepad_axis",
      "gamepad_button",
      "import",
      "from",
      "export",
      "as",
    ],
    typeKeywords: ["i32", "i64", "f32", "f64", "bool", "void", "str"],
    tokenizer: {
      root: [
        [/#.*$/, "comment"],
        [/"(?:\\.|[^"\\])*"/, "string"],
        [/\b\d+\.\d+\b/, "number.float"],
        [/\b\d+\b/, "number"],
        [
          /[a-zA-Z_][\w]*/,
          {
            cases: {
              "@keywords": "keyword",
              "@typeKeywords": "type",
              "@default": "identifier",
            },
          },
        ],
        [/[{}()\[\]]/, "@brackets"],
        [/[<>]=?|[!=]=|[-+*/%=]/, "operator"],
        [/[:.,]/, "delimiter"],
        [/\s+/, "white"],
      ],
    },
  });

  monaco.languages.setLanguageConfiguration(JUNI_LANGUAGE_ID, {
    comments: { lineComment: "#" },
    brackets: [
      ["(", ")"],
      ["[", "]"],
      ["{", "}"],
    ],
    autoClosingPairs: [
      { open: "(", close: ")" },
      { open: '"', close: '"' },
    ],
  });
}
